name: Auto Build and Package for Windows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify files in directory  # 新增步骤
        run: dir
        shell: cmd
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome Browser
        run: |
          choco install googlechrome --yes
      - name: Build and Package
        run: |
          pyinstaller --onefile --windowed --icon=app.ico --noupx --add-data "app.ico;." --hidden-import=win32gui --hidden-import=requests --hidden-import=keyboard --hidden-import=mouse --hidden-import=wmi --hidden-import=sv_ttk --hidden-import=PIL --hidden-import=win11toast chrome_manager.py
          echo "Build completed. Check dist/ folder for the EXE file."
        shell: cmd
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-manager-package
          path: dist/
